# Generated by Django 6.0 on 2025-12-30 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('activar_front', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='paginasusuario.datospersonales')),
            ],
        ),
    ]
