# Generated by Django 6.0 on 2025-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0002_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificados/'),
        ),
    ]
