# Generated by Django 6.0 on 2025-12-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0003_remove_certificado_ruta_archivo_certificado_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='archivo',
        ),
        migrations.AddField(
            model_name='certificado',
            name='ruta_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
