# Generated by Django 6.0 on 2025-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0004_remove_certificado_archivo_certificado_ruta_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='ruta_archivo',
            field=models.CharField(default='archivo_desconocido.pdf', max_length=255),
            preserve_default=False,
        ),
    ]
