# Generated by Django 6.0 on 2025-12-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0005_alter_certificado_ruta_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(default='certificados/placeholder.pdf', upload_to='certificados/'),
            preserve_default=False,
        ),
    ]
