# Generated by Django 6.0 on 2025-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0006_remove_certificado_ruta_archivo_certificado_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
    ]
