# Generated by Django 6.0 on 2025-12-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0008_certificado_archivo_url_alter_certificado_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='archivo_url',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(default='temporal.pdf', upload_to=''),
            preserve_default=False,
        ),
    ]
