# Generated by Django 6.0 on 2025-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0009_remove_certificado_archivo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='archivo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
