"""
Django settings for hojadevida project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
load_dotenv()




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-tfn_-#+!)0h=s6sf5zoj7z2#6sg3^mmd368h7g@w3tqk0%2x^3'
SECRET_KEY=os.environ.get('SECRET_KEY',default='your secret key')
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = 'RENDER' not in os.environ
DEBUG = os.getenv("DEBUG", "False") == "True"


#VERSION ANTERIOR COMENTADA
#-----------------------------------------------------------------
# ALLOWED_HOSTS = []
# RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL')
# if RENDER_EXTERNAL_HOSTNAME:
# 	ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
#------------------------------------------------------------------
ALLOWED_HOSTS = ['localhost', '127.0.0.1'] # Para que siga funcionando en tu PC
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME') # Ojo: Render usa 'RENDER_EXTERNAL_HOSTNAME'
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    # También es bueno agregar el dominio base si el anterior falla
    ALLOWED_HOSTS.append('.onrender.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paginasusuario',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'hojadevida.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hojadevida.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#ESTA BASE DE DATOS ES LA BUENA
#-------------------------------------------------------------------------------
# DATABASES = {
#     'default': dj_database_url.config(
#         default='external url',
#         conn_max_age=600
#     )
# }
#---------------------------------------------------------------------------------

DATABASES = {
    'default': dj_database_url.config(
        #default='external url',
        default = os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Esto es lo que permite que WhiteNoise (que tienes en tu lista) funcione en Render
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Esto le dice a Django dónde buscar archivos estáticos en tus carpetas
STATICFILES_DIRS = [
    BASE_DIR / 'paginasusuario' / 'static',
]

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

# AZURE_ACCOUNT_NAME = 'davidcertificados'
# AZURE_ACCOUNT_KEY = 'clave'
# AZURE_CONTAINER = 'certificados'

# AZURE_CUSTOM_DOMAIN = f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net"

# AZURE_LOCATION = ''
# AZURE_OVERWRITE_FILES = False

# MEDIA_URL = f"https://{AZURE_CUSTOM_DOMAIN}/{AZURE_CONTAINER}/"

DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

AZURE_ACCOUNT_NAME = os.environ.get('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.environ.get('AZURE_ACCOUNT_KEY')
AZURE_CONTAINER = os.environ.get('AZURE_CONTAINER')

AZURE_CUSTOM_DOMAIN = f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net"
MEDIA_URL = f"https://{AZURE_CUSTOM_DOMAIN}/{AZURE_CONTAINER}/"

#print("DB_URL =", os.getenv("DATABASE_URL"))



STATIC_URL = '/static/'

